language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
install:
  - cpanm --quiet --installdeps --notest .
script:
  - perl Makefile.PL
  - make
  - make dist
  - tar zxvf *.tar.gz
  - cd p5-App-DSC-DataTool-*[0-9]
  - perl Makefile.PL
  - make
  - RELEASE_TESTING=1 make test
