#!/bin/sh

if [ -n "$1" ]; then
  files="$*"
else
  files="`find lib t -type f -name '*.pm'` `find t -type f -name '*.t'` bin/* Makefile.PL `find contrib -type f -name '*.pl'`"
fi

if ! perl -e 'use Perl::Tidy 20140711;' >/dev/null 2>/dev/null; then
  echo 'Perl::Tidy 20140711 required'
  exit 1
fi

exec perltidy --pro=t/perltidyrc $files
