name: test
on: pull_request
jobs:
  test:
    runs-on: docker
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y python3-maxminddb python3-yaml wget python3-pip
        python3 -m pip install --upgrade pip
        pip install .
    - name: Test
      run: |
        cd tests
        rm ipv4-address-space.csv ipv6-unicast-address-assignments.csv
        wget https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.csv
        wget https://www.iana.org/assignments/ipv6-unicast-address-assignments/ipv6-unicast-address-assignments.csv
        ./test.sh
