.TH "dsc-datatool-output influxdb" "7"
.SH NAME
InfluxDB \- InfluxDB output.
.SH SYNOPSIS
.SY dsc-datatool
.B \-\-output
.I """;InfluxDB;<options...>"""
.YS
.SH DESCRIPTION
This output generates InfluxDB importable output to stdout or to a specified
file.
.SH OPTIONS
.TP
.BR timestamp =[start|stop]
Choose which timestamp from the dataset to use in the InfluxDB output to
specify when the metrics took place.

Default to
.I start
timestamp.
.TP
.BR file =<filename>
Specify a file to output to instead of stdout.
.TP
.BR append
If given, the output will be appended to the file specified rather then
overwritten.
.TP
.BR dml
Add a
.I "# DML"
header to the output.
.TP
.BR database =name
If
.I dml
is used, this can be used to specify which database the output should be
imported into.
.LP
.SH "SEE ALSO"
.BR dsc-datatool (1),
.BR influx (1)
.SH AUTHORS
Jerry Lundström, DNS-OARC
.LP
Maintained by DNS-OARC
.LP
.RS
.I https://www.dns-oarc.net/tools/dsc
.RE
.LP
.SH BUGS
For issues and feature requests please use:
.LP
.RS
\fIhttps://github.com/DNS-OARC/dsc-datatool/issues\fP
.RE
.LP
For question and help please use:
.LP
.RS
\fIhttps://lists.dns-oarc.net/mailman/listinfo/dsc\fP
.RE
.LP
